# Generated by Django 4.2.4 on 2023-11-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='usern',
            new_name='username',
        ),
    ]
